name: Fetch Steam Game Data

on:
  workflow_dispatch:  # Allows manual runs
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  fetch_games:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Steam Data
        run: |
          curl -s "https://api.steampowered.com/ISteamApps/GetAppList/v2/" | jq . > steam_games.json

      - name: Commit and Push Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add steam_games.json
          git commit -m "Update Steam game data"
          git push
